name: Rebuild (New Year)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  reddit-streak:
    name: Reddit 800 day streak
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s 'https://www.reddit.com/svc/shreddit/graphql' \
              -H 'content-type: application/json' \
              -b 'csrf_token=example' \
              -H 'user-agent: Mozilla/5.0 (Fake)' \
              --data-raw '{"operation":"AchievementTrophyById","variables":{"id":"800-day-streak","name":"scholesmafia","imageMaxWidth":500},"csrf_token":"example"}' \
            | jq .data.redditorInfoByName.trophyCase.achievementTrophyById.statistics.usersUnlockedCount
